name: Build bundle-gen
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker tags
        id: metabase
        uses: docker/metadata-action@v3
        with:
          images:
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=schedule,pattern=builder-{{date 'YYYYMMDD'}}
            builder

      - name: Build and push base container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.bundle-gen
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metabase.outputs.tags }}
          labels: ${{ steps.metabase.outputs.labels }}
